"""empty message

Revision ID: 17554d71c9f8
Revises: ab49d3f1f22a
Create Date: 2019-09-28 12:54:57.821058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17554d71c9f8'
down_revision = 'ab49d3f1f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shows')
    # ### end Alembic commands ###
