"""empty message

Revision ID: ae65ebd9a3fb
Revises: 17554d71c9f8
Create Date: 2019-09-28 13:31:33.974736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae65ebd9a3fb'
down_revision = '17554d71c9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'venue_id')
    # ### end Alembic commands ###
